TOL = 2
PCT_TOL = 0.005

FAMILY_MAP = {
    'cash': 'Cuentas a la vista',
    'saving-account': 'Cuentas a la vista',
    'certificate-deposit': 'Depósitos',
    'term-deposit': 'Depósitos',
    'bond': 'Renta fija',
    'money-market': 'Renta fija',
    'mutual-fund': 'Fondos de inversión',
    'etf': 'Renta variable',
    'common-share': 'Renta variable',
    'preferred-share': 'Renta variable',
    'private-equity': 'Otros productos de inversión',
    'hedge-fund': 'Otros productos de inversión',
    'structured-debt': 'Notas estructuradas',
}

KPI_SUBS = {
    'CUENTAS A LA VISTA': ['cash', 'saving-account', 'cash_account'],
    'DEPÓSITOS': ['certificate-deposit', 'term-deposit'],
    'RENTA FIJA': ['bond', 'money-market'],
    'FONDOS DE INVERSIÓN': ['mutual-fund'],
    'RENTA VARIABLE': ['common-share', 'preferred-share', 'etf'],
    'OTROS PRODUCTOS DE INVERSIÓN': ['private-equity', 'hedge-fund'],
    'NOTAS ESTRUCTURADAS': ['structured-debt', 'structured-certificate'],
    'CARTERAS': ['portfolio'],
    'SICAV': ['sicav'],
    'DERIVADOS': ['derivative'],
}

ASSET_CLASS_MAP_MD = {
    'real-estate':       ['Funds', 'Real Estate'],
    'real_estate':       ['Funds', 'Real Estate'],
    'other_inv':         ['Equities', 'Others'],
    'other-inv':         ['Equities', 'Others'],
    'equity':            ['Funds', 'Equity'],
    'fund':              ['Funds', 'Equity'],
    'allocation':        ['Funds', 'Allocation'],
    'fixed-income':      ['Funds', 'Fixed Income'],
    'fixed_income':      ['Funds', 'Fixed Income'],
    'money-market':      ['Funds', 'Money Market'],
    'money_market':      ['Funds', 'Money Market'],
    'other_financials':  ['Funds', 'Other financials'],
    'other-financials':  ['Funds', 'Other financials'],
    'cash':              ['Cash', 'Cash & Equivalents'],
    'cash_equivalents':  ['Cash', 'Cash & Equivalents'],
    'liability':         ['Liabilities', 'Liabilities'],
}

FONDOS_GROUPS_MD = {
    'equity', 'fund', 'fixed-income', 'fixed_income',
    'money-market', 'money_market', 'allocation',
    'other_financials', 'other-financials',
}

MD_COLUMNS = [
    'symbol', 'date', 'investor_account', 'quantity', 'cost_basis',
    'market_value', 'local_market_value', 'position_gl', 'asset_description',
    'investor_id', 'currency', 'custodian', 'asset_type', 'asset_class',
    'sub_asset_class', 'sector', 'maturity_date', 'initial_fx_rate',
    'current_fx_rate', 'market_price', 'valuation_date',
    'Allocation_Equity', 'Allocation_Fixed Income', 'Allocation_Money Market',
    'Allocation_Other financials', 'Allocation_Cash & Equivalents',
    'Alpha_1', 'Beta_1', 'TER_1', 'TIR_1', 'Volatility_1', 'Duration_1', 'Cupon_1', 'Dividend_1', 'PER_1',
    'Currency_AUD', 'Currency_BRL', 'Currency_CAD', 'Currency_CHF', 'Currency_CNY',
    'Currency_DKK', 'Currency_EUR', 'Currency_GBP', 'Currency_HKD', 'Currency_INR',
    'Currency_JPY', 'Currency_KRW', 'Currency_MXN', 'Currency_NOK', 'Currency_SEK',
    'Currency_SGD', 'Currency_TWD', 'Currency_USD', 'Currency_Others',
    'Rating Grade_AAA', 'Rating Grade_AA', 'Rating Grade_A', 'Rating Grade_BBB',
    'Rating Grade_BB', 'Rating Grade_B', 'Rating Grade_Sin datos', 'Rating Grade_Others',
    'Rating_AAA', 'Rating_AA', 'Rating_A', 'Rating_BBB', 'Rating_BB',
    'Rating_B', 'Rating_Below B', 'Rating_NR', 'Rating_Others',
    'Sector_FI_Corporate Bond', 'Sector_FI_Government', 'Sector_FI_Gov. Related',
    'Sector_FI_Asset Backed', 'Sector_FI_Covered Bond', 'Sector_FI_Cash & Equiv.',
    'Sector_EQ_Technology', 'Sector_EQ_Financial Services', 'Sector_EQ_Healthcare',
    'Sector_EQ_Industrials', 'Sector_EQ_Consumer Cyclical', 'Sector_EQ_Consumer Defensive',
    'Sector_EQ_Communication Services', 'Sector_EQ_Energy', 'Sector_EQ_Basic Materials',
    'Sector_EQ_Real Estate', 'Sector_EQ_Utilities', 'Sector_EQ_Others',
    'Sector_Basic Materials', 'Sector_Communication Services', 'Sector_Consumer Cyclical',
    'Sector_Consumer Defensive', 'Sector_Energy', 'Sector_Financial Services',
    'Sector_Healthcare', 'Sector_Industrials', 'Sector_Real Estate',
    'Sector_Technology', 'Sector_Others',
    'Style_Large Growth', 'Style_Large Core', 'Style_Large Value',
    'Style_Mid Growth', 'Style_Mid Core', 'Style_Mid Value',
    'Style_Small Growth', 'Style_Small Core', 'Style_Small Value', 'Style_Others',
    'Maturity_<182d', 'Maturity_182d-365d', 'Maturity_1-3y', 'Maturity_3-5y',
    'Maturity_5-7y', 'Maturity_7-10y', 'Maturity_10-15y', 'Maturity_15-20y',
    'Maturity_20-30y', 'Maturity_>30y',
    'Region_EQ_North America', 'Region_EQ_Europe Dev', 'Region_EQ_UK',
    'Region_EQ_Japan', 'Region_EQ_Asia Dev', 'Region_EQ_Asia Emrg',
    'Region_EQ_Australasia', 'Region_EQ_LATAM', 'Region_EQ_Europe Emrg', 'Region_EQ_Africa/ME',
    'Region_FI_North America', 'Region_FI_Europe Dev', 'Region_FI_UK',
    'Region_FI_Japan', 'Region_FI_Asia Dev', 'Region_FI_Asia Emrg',
    'Region_FI_Australasia', 'Region_FI_LATAM', 'Region_FI_Europe Emrg', 'Region_FI_Africa/ME',
    'Revenue VI_Eurozone', 'Revenue VI_Europe Ex eur', 'Revenue VI_USA', 'Revenue VI_Canada',
    'Revenue VI_Japan', 'Revenue VI_Developed Asia', 'Revenue VI_Australasia',
    'Revenue VI_Emerging Asia', 'Revenue VI_Emerging Europe', 'Revenue VI_LATAM',
    'Revenue VI_Africa', 'Revenue VI_Middle East', 'Revenue VI_UK', 'Revenue VI_Others',
    'Highest_Rating', 'final_market_value', 'asset_class_group',
    'TIR', 'Rating', 'Duration', 'Cupon', 'Maturity', 'PER', 'Dividend',
    'Volatility', 'TER', 'Alpha', 'Beta', 'Region', 'isin',
    'last_price_update', 'risk_type', 'service_type',
    'investor', 'contact', 'investor_name',
]
